// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1K8dlsdcg37j--LfWcNvYPP5jDfnRtAM',
    appId: '1:129987129650:web:82953b9ff4cc08beca272b',
    messagingSenderId: '129987129650',
    projectId: 'apptallerm3',
    authDomain: 'apptallerm3.firebaseapp.com',
    databaseURL: 'https://apptallerm3-default-rtdb.firebaseio.com',
    storageBucket: 'apptallerm3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQe4ec9GDaaeycSctFcF9t6ybeu9thkZw',
    appId: '1:129987129650:android:ee8dc1189de0572dca272b',
    messagingSenderId: '129987129650',
    projectId: 'apptallerm3',
    databaseURL: 'https://apptallerm3-default-rtdb.firebaseio.com',
    storageBucket: 'apptallerm3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO5cNTxWTjqWN0KNVpc4qo6fRwUyIRnYY',
    appId: '1:129987129650:ios:e42ed936ed175b44ca272b',
    messagingSenderId: '129987129650',
    projectId: 'apptallerm3',
    databaseURL: 'https://apptallerm3-default-rtdb.firebaseio.com',
    storageBucket: 'apptallerm3.appspot.com',
    iosBundleId: 'com.example.taller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO5cNTxWTjqWN0KNVpc4qo6fRwUyIRnYY',
    appId: '1:129987129650:ios:e42ed936ed175b44ca272b',
    messagingSenderId: '129987129650',
    projectId: 'apptallerm3',
    databaseURL: 'https://apptallerm3-default-rtdb.firebaseio.com',
    storageBucket: 'apptallerm3.appspot.com',
    iosBundleId: 'com.example.taller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1K8dlsdcg37j--LfWcNvYPP5jDfnRtAM',
    appId: '1:129987129650:web:ea84d75e3adaac7dca272b',
    messagingSenderId: '129987129650',
    projectId: 'apptallerm3',
    authDomain: 'apptallerm3.firebaseapp.com',
    databaseURL: 'https://apptallerm3-default-rtdb.firebaseio.com',
    storageBucket: 'apptallerm3.appspot.com',
  );

}